"""empty message

Revision ID: 2629376e2b77
Revises: 16f6aae530ab
Create Date: 2025-09-13 19:34:53.210881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2629376e2b77'
down_revision = '16f6aae530ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
